DROP DATABASE IF EXISTS ifrs;
CREATE DATABASE ifrs;
\c ifrs;

CREATE TABLE aluno (
    id serial primary key,
    nome text
);

INSERT INTO aluno (nome) VALUES 
('geraldo'),
('canrobert');

REVOKE ALL PRIVILEGES ON DATABASE ifrs FROM igor;
DROP USER igor;
REVOKE ALL PRIVILEGES ON DATABASE ifrs FROM betito;
DROP USER betito;
REVOKE ALL PRIVILEGES ON DATABASE ifrs FROM marcio;
DROP USER marcio;


CREATE USER igor WITH PASSWORD '123' SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE ifrs TO igor;

CREATE USER betito WITH PASSWORD '123';
GRANT INSERT ON ALL TABLES IN SCHEMA public to betito;
GRANT SELECT ON ALL TABLES IN SCHEMA public to betito;
GRANT UPDATE ON ALL TABLES IN SCHEMA public to betito;

CREATE USER marcio WITH PASSWORD '123' CREATEDB;
GRANT SELECT ON ALL TABLES IN SCHEMA public to marcio;



